<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260223/blob/main/20260321.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import urllib.request as req
import json
import pandas as pd

# name: 1 2 3...
def download_danmu(serial, fp, episode):
    pat = "https://api.gamer.com.tw/anime/v1/danmu.php?videoSn={}&geo=TW%2CHK"
    url = pat.format(serial)
    print(url)
    f = req.urlopen(url)
    content = f.read()
    content = json.loads(content)
    danmu = content["data"]["danmu"]

    df = pd.DataFrame(danmu)
    # 增加一行, 並且設定成同一個值 取行: df[行名稱]
    df["episode"] = episode
    df.to_csv(fp, encoding="utf-8")

download_danmu(35242, "xzxxxxx.csv", "10")

https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35242&geo=TW%2CHK

In [10]:
import os

import urllib.request as req
import bs4 as bs

h = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0",
}

# url = "https://ani.gamer.com.tw/animeVideo.php?sn=35241"
url = "https://github.com/Elwing-Chou/tibame20260223/raw/refs/heads/main/baha.html"
r = req.Request(url, headers=h)
resp = req.urlopen(r)
content = resp.read()
html = bs.BeautifulSoup(content)

save_dir = "baha"
# 新創資料夾: 如果資料夾不存在, make起來
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

for a in html.find_all("a"):
    # 找到對象區塊以後: 屬性(["href"]) 文字(.get_text())
    href = a["href"]
    if href.startswith("?sn="):
        print("下載:", href)
        sn = href.replace("?sn=", "")
        episode = a.get_text()
        print("集數:", episode)
        fp = save_dir + "/" + sn + ".csv"
        print("儲存位置:", fp)
        download_danmu(sn, fp, episode)

下載: ?sn=35241
集數: 1
儲存位置: baha/35241.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35241&geo=TW%2CHK
下載: ?sn=35242
集數: 2
儲存位置: baha/35242.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35242&geo=TW%2CHK
下載: ?sn=35243
集數: 3
儲存位置: baha/35243.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35243&geo=TW%2CHK
下載: ?sn=35244
集數: 4
儲存位置: baha/35244.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35244&geo=TW%2CHK
下載: ?sn=35445
集數: 5
儲存位置: baha/35445.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35445&geo=TW%2CHK
下載: ?sn=35446
集數: 6
儲存位置: baha/35446.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35446&geo=TW%2CHK
下載: ?sn=35447
集數: 7
儲存位置: baha/35447.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35447&geo=TW%2CHK
下載: ?sn=35660
集數: 8
儲存位置: baha/35660.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35660&geo=TW%2CHK
下載: ?sn=35781
集數: 9
儲存位置: baha/35781.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35781&geo=TW%2CHK
下載: ?sn=35845
集數: 10
儲存位置: baha/35845.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=35845&geo=TW%2CHK
下載: ?sn=36046
集數: 11
儲存位置: baha/36046.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36046&geo=TW%2CHK
下載: ?sn=36128
集數: 12
儲存位置: baha/36128.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36128&geo=TW%2CHK
下載: ?sn=36196
集數: 13
儲存位置: baha/36196.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36196&geo=TW%2CHK
下載: ?sn=36260
集數: 14
儲存位置: baha/36260.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36260&geo=TW%2CHK
下載: ?sn=36371
集數: 15
儲存位置: baha/36371.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36371&geo=TW%2CHK
下載: ?sn=36553
集數: 16
儲存位置: baha/36553.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36553&geo=TW%2CHK
下載: ?sn=36554
集數: 17
儲存位置: baha/36554.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36554&geo=TW%2CHK
下載: ?sn=36861
集數: 18
儲存位置: baha/36861.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36861&geo=TW%2CHK
下載: ?sn=36862
集數: 19
儲存位置: baha/36862.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36862&geo=TW%2CHK
下載: ?sn=36991
集數: 20
儲存位置: baha/36991.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=36991&geo=TW%2CHK
下載: ?sn=37034
集數: 21
儲存位置: baha/37034.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37034&geo=TW%2CHK
下載: ?sn=37100
集數: 22
儲存位置: baha/37100.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37100&geo=TW%2CHK
下載: ?sn=37237
集數: 23
儲存位置: baha/37237.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37237&geo=TW%2CHK
下載: ?sn=37362
集數: 24
儲存位置: baha/37362.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37362&geo=TW%2CHK
下載: ?sn=37407
集數: 25
儲存位置: baha/37407.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37407&geo=TW%2CHK
下載: ?sn=37408
集數: 26
儲存位置: baha/37408.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37408&geo=TW%2CHK
下載: ?sn=37628
集數: 27
儲存位置: baha/37628.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37628&geo=TW%2CHK
下載: ?sn=37668
集數: 28
儲存位置: baha/37668.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=37668&geo=TW%2CHK
下載: ?sn=39208
集數: 1
儲存位置: baha/39208.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39208&geo=TW%2CHK
下載: ?sn=39209
集數: 2
儲存位置: baha/39209.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39209&geo=TW%2CHK
下載: ?sn=39210
集數: 3
儲存位置: baha/39210.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39210&geo=TW%2CHK
下載: ?sn=39211
集數: 4
儲存位置: baha/39211.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39211&geo=TW%2CHK
下載: ?sn=39212
集數: 5
儲存位置: baha/39212.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39212&geo=TW%2CHK
下載: ?sn=39213
集數: 6
儲存位置: baha/39213.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39213&geo=TW%2CHK
下載: ?sn=39214
集數: 7
儲存位置: baha/39214.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39214&geo=TW%2CHK
下載: ?sn=39215
集數: 8
儲存位置: baha/39215.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39215&geo=TW%2CHK
下載: ?sn=39216
集數: 9
儲存位置: baha/39216.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39216&geo=TW%2CHK
下載: ?sn=39217
集數: 10
儲存位置: baha/39217.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39217&geo=TW%2CHK
下載: ?sn=39218
集數: 11
儲存位置: baha/39218.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39218&geo=TW%2CHK
下載: ?sn=39219
集數: 12
儲存位置: baha/39219.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39219&geo=TW%2CHK
下載: ?sn=39220
集數: 13
儲存位置: baha/39220.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39220&geo=TW%2CHK
下載: ?sn=39221
集數: 14
儲存位置: baha/39221.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39221&geo=TW%2CHK
下載: ?sn=39222
集數: 15
儲存位置: baha/39222.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39222&geo=TW%2CHK
下載: ?sn=39223
集數: 16
儲存位置: baha/39223.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39223&geo=TW%2CHK
下載: ?sn=39224
集數: 17
儲存位置: baha/39224.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39224&geo=TW%2CHK
下載: ?sn=39225
集數: 18
儲存位置: baha/39225.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39225&geo=TW%2CHK
下載: ?sn=39226
集數: 19
儲存位置: baha/39226.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39226&geo=TW%2CHK
下載: ?sn=39227
集數: 20
儲存位置: baha/39227.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39227&geo=TW%2CHK
下載: ?sn=39228
集數: 21
儲存位置: baha/39228.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39228&geo=TW%2CHK
下載: ?sn=39229
集數: 22
儲存位置: baha/39229.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39229&geo=TW%2CHK
下載: ?sn=39230
集數: 23
儲存位置: baha/39230.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39230&geo=TW%2CHK
下載: ?sn=39231
集數: 24
儲存位置: baha/39231.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39231&geo=TW%2CHK
下載: ?sn=39232
集數: 25
儲存位置: baha/39232.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39232&geo=TW%2CHK
下載: ?sn=39233
集數: 26
儲存位置: baha/39233.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39233&geo=TW%2CHK
下載: ?sn=39234
集數: 27
儲存位置: baha/39234.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39234&geo=TW%2CHK
下載: ?sn=39235
集數: 28
儲存位置: baha/39235.csv
https://api.gamer.com.tw/anime/v1/danmu.php?videoSn=39235&geo=TW%2CHK

In [40]:
# 把所有csv聚集成一個大的表格
# 針對每一個出現過的userid
# 把他發過的danmu拿出來

import glob

total_df = []
for fp in glob.glob("baha/*.csv"):
    df = pd.read_csv(fp, encoding="utf-8", index_col=0)
    total_df.append(df)

total = pd.concat(total_df, axis=0)
total = total.sort_values("episode")
# 取行: [行名稱]
# 取獨特: unique()/value_counts()
users = total["userid"].unique()

# drive/MyDrive/result
save_dir = "result"
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

for u in users:
    fil = total["userid"] == u
    fp = save_dir + "/" + u + ".csv"
    total[fil].to_csv(fp, encoding="utf-8", index=False)

In [36]:
# demo
users = total["userid"].unique()
# pandas所有操作都是對每一格做的
test = users[0]
total["userid"] == test
# total["time"] + 9999

123      True
122     False
121     False
120     False
119     False
        ...
74      False
73      False
103     False
72      False
3000    False
Name: userid, Length: 84210, dtype: bool

In [19]:
# demo: concat(合併)
# axis參數: 決定是何種方向(0 1)
df1 = pd.DataFrame([
    [1, 2],
    [3, 4]
])
df2 = pd.DataFrame([
    [5, 6],
    [7, 8]
])
pd.concat([df1, df2], axis=1)

   0  1  0  1
0  1  2  5  6
1  3  4  7  8

In [25]:
# pandas兩大操作: 過濾/轉換

# 過濾: df[跟你資料筆數依樣多的true/false]
# demo

df = pd.DataFrame([
    [1, 2],
    [3, 4],
    [5, 6]
])

fil = [False, True, False]
df[fil]

   0  1
1  3  4

In [ ]:
# 如果你要下載colab上的整個資料夾
!zip -r /content/file.zip /content/result

In [42]:
# 掛階雲端硬碟
fp = "drive/MyDrive/a.txt"
f = open(fp, "w", encoding="utf-8")
f.write("asfdfads")
f.close()